# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Test-MockCommand
version:      0.01
version_from: lib/Test/MockCommand.pm
installdirs:  site
requires:
    Carp:                          0
    Data::Dumper:                  0
    Errno:                         0
    POSIX:                         0
    Symbol:                        0
    Tie::Handle:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
